-d C:\Users\Gebruiker\Documents\gomulu_odev\impl\gwsynthesis\gomulu_odev.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\Gebruiker\Documents\gomulu_odev\src\gomulu_odev.cst
-cfg C:\Users\Gebruiker\Documents\gomulu_odev\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
